name: spgdmm-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy>=1.24
  - pandas>=2.0
  - xarray>=2023.1
  - scipy>=1.10
  - scikit-learn>=1.3
  - scikit-image>=0.21
  - matplotlib>=3.7
  - pymc>=5.0
  - arviz>=0.17
  - nutpie>=0.10
  - jupyterlab
  - pip
  - pip:
      - dms-variants>=0.8
      - ISLP>=0.3
      - json-tricks>=3.16
      - properscoring>=0.1
      - -e ./spgdmm
